server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/db;DB_CLOSE_DELAY=-1
  data:
    rest:
      base-path: /api

liquibase:
  change-log: classpath:/db/master.xml
